
# logout user

POST http://localhost:3000/auth/logout HTTP/1.1

Content-Type: application/json

Set-Cookie: eccubeToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTY4NjY2NjU5LCJleH;

{}