
# register user
POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "jonny",
    "lastName": "boy",
    "password": "Qwertyuiop12345!",
    "email": "jonnn@gmail.com",
    "type": "Customer"
}

