
# save Mollie access token

POST https://localhost:443/mollie/token HTTP/1.1
Content-Type: application/json
Cookie: eccubeToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJlY2N1YmUiLCJpc3MiOiJlY2N1YmUiLCJpYXQiOjE3MDE3ODY4MTEsImd1ZXN0IjpmYWxzZSwidXNlcklkIjoiYWJjZjk4ZGYtMjZkNi00OGRhLWE2YTMtZWFhMGRhMTVmZGU0IiwiZXhwIjoxNzAyMzkxNjExfQ.N5m7egMGlG0oWt0i_ZNZ1nTcJpkm4Kwf-5myOKDn8Ks

{
    "token": "access_655fAzxSzvKuCEEGgzRWpuM9DRtAkp"
}